<?php
// app/Http/Controllers/CodeExecutorController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

class CodeExecutorController extends Controller
{
    public function index()
    {

            return view('code-executor.index');

    }

    public function execute(Request $request)
    {
        $request->validate([
            'code' => 'required|string|max:50000',
            'type' => 'required|in:react,html,javascript,vue'
        ]);

        $code = $request->input('code');
        $type = $request->input('type');
        $libraries = $request->input('libraries', []);

        try {
            $htmlContent = $this->generateHtmlContent($code, $type, $libraries);

            return response()->json([
                'success' => true,
                'html' => $htmlContent
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error: ' . $e->getMessage()
            ], 500);
        }
    }

    public function download(Request $request)
    {
        $request->validate([
            'code' => 'required|string',
            'type' => 'required|in:react,html,javascript,vue',
            'projectName' => 'nullable|string|max:100'
        ]);

        $code = $request->input('code');
        $type = $request->input('type');
        $projectName = $request->input('projectName', 'my-app');
        
        try {
            if ($type === 'react') {
                return $this->downloadReactProject($code, $projectName);
            } elseif ($type === 'html') {
                return $this->downloadHtmlProject($code, $projectName);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'Download not supported for this type yet'
                ], 400);
            }
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Download failed: ' . $e->getMessage()
            ], 500);
        }
    }

    public function uploadGitRepo(Request $request)
    {
        $request->validate([
            'repo_url' => 'required|url'
        ]);

        $repoUrl = $request->input('repo_url');

        try {
            // For now, we'll just return a message
            // Full implementation would require server-side git clone
            return response()->json([
                'success' => false,
                'message' => 'Git repository preview is under development. Please download and run locally for now.'
            ], 501);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error: ' . $e->getMessage()
            ], 500);
        }
    }

    private function downloadReactProject($code, $projectName)
    {
        $projectName = preg_replace('/[^a-zA-Z0-9-_]/', '', $projectName);
        $tempDir = storage_path('app/temp/' . $projectName . '_' . time());
        
        // Create project structure
        mkdir($tempDir, 0755, true);
        mkdir($tempDir . '/src', 0755, true);
        mkdir($tempDir . '/public', 0755, true);

        // Create package.json
        $packageJson = [
            'name' => $projectName,
            'version' => '0.1.0',
            'private' => true,
            'dependencies' => [
                'react' => '^18.2.0',
                'react-dom' => '^18.2.0',
                'react-scripts' => '5.0.1'
            ],
            'scripts' => [
                'start' => 'react-scripts start',
                'build' => 'react-scripts build',
                'test' => 'react-scripts test',
                'eject' => 'react-scripts eject'
            ],
            'eslintConfig' => [
                'extends' => ['react-app']
            ],
            'browserslist' => [
                'production' => ['>0.2%', 'not dead', 'not op_mini all'],
                'development' => ['last 1 chrome version', 'last 1 firefox version', 'last 1 safari version']
            ]
        ];
        file_put_contents($tempDir . '/package.json', json_encode($packageJson, JSON_PRETTY_PRINT));

        // Create public/index.html
        $indexHtml = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="Generated by AI App Builder" />
    <title>$projectName</title>
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
</body>
</html>
HTML;
        file_put_contents($tempDir . '/public/index.html', $indexHtml);

        // Convert inline React code to proper React component
        $appJs = $this->convertToReactComponent($code);
        file_put_contents($tempDir . '/src/App.js', $appJs);

        // Create index.js
        $indexJs = <<<JS
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
JS;
        file_put_contents($tempDir . '/src/index.js', $indexJs);

        // Create .gitignore
        $gitignore = <<<TXT
# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
TXT;
        file_put_contents($tempDir . '/.gitignore', $gitignore);

        // Create README.md
        $readme = <<<MD
# $projectName

This project was generated by AI App Builder.

## Available Scripts

In the project directory, you can run:

### `npm install`
First, install the dependencies.

### `npm start`
Runs the app in development mode.
Open [http://localhost:3000](http://localhost:3000) to view it in your browser.

### `npm run build`
Builds the app for production to the `build` folder.

## Learn More

You can learn more in the [Create React App documentation](https://facebook.github.io/create-react-app/docs/getting-started).
MD;
        file_put_contents($tempDir . '/README.md', $readme);

        // Create ZIP file
        $zipPath = storage_path('app/temp/' . $projectName . '.zip');
        $zip = new ZipArchive();
        
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {
            $files = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($tempDir),
                \RecursiveIteratorIterator::LEAVES_ONLY
            );

            foreach ($files as $file) {
                if (!$file->isDir()) {
                    $filePath = $file->getRealPath();
                    $relativePath = substr($filePath, strlen($tempDir) + 1);
                    $zip->addFile($filePath, $projectName . '/' . $relativePath);
                }
            }

            $zip->close();

            // Clean up temp directory
            $this->deleteDirectory($tempDir);

            return response()->download($zipPath)->deleteFileAfterSend(true);
        }

        throw new \Exception('Failed to create ZIP file');
    }

    private function downloadHtmlProject($code, $projectName)
    {
        $projectName = preg_replace('/[^a-zA-Z0-9-_]/', '', $projectName);
        $tempDir = storage_path('app/temp/' . $projectName . '_' . time());
        
        mkdir($tempDir, 0755, true);

        // Save HTML file
        file_put_contents($tempDir . '/index.html', $code);

        // Create README
        $readme = <<<MD
# $projectName

This HTML project was generated by AI App Builder.

Simply open `index.html` in your browser to view the application.
MD;
        file_put_contents($tempDir . '/README.md', $readme);

        // Create ZIP
        $zipPath = storage_path('app/temp/' . $projectName . '.zip');
        $zip = new ZipArchive();
        
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {
            $files = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($tempDir),
                \RecursiveIteratorIterator::LEAVES_ONLY
            );

            foreach ($files as $file) {
                if (!$file->isDir()) {
                    $filePath = $file->getRealPath();
                    $relativePath = substr($filePath, strlen($tempDir) + 1);
                    $zip->addFile($filePath, $projectName . '/' . $relativePath);
                }
            }

            $zip->close();
            $this->deleteDirectory($tempDir);

            return response()->download($zipPath)->deleteFileAfterSend(true);
        }

        throw new \Exception('Failed to create ZIP file');
    }

    private function convertToReactComponent($code)
    {
        // Try to extract the App component
        if (preg_match('/function App\(\)\s*\{[\s\S]*?\}/m', $code, $matches)) {
            return "import React from 'react';\n\n" . $matches[0] . "\n\nexport default App;";
        }

        // If no App function found, wrap the code
        return <<<JS
import React from 'react';

function App() {
  return (
    <div className="App">
      <p>Please modify this component</p>
    </div>
  );
}

export default App;
JS;
    }

    private function deleteDirectory($dir)
    {
        if (!file_exists($dir)) {
            return;
        }

        $files = array_diff(scandir($dir), ['.', '..']);
        
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            is_dir($path) ? $this->deleteDirectory($path) : unlink($path);
        }
        
        rmdir($dir);
    }

    private function generateHtmlContent($code, $type, $libraries = [])
    {
        $libraryScripts = '';
        foreach ($libraries as $lib) {
            $libraryScripts .= "<script src=\"{$lib}\"></script>\n";
        }

        switch ($type) {
            case 'react':
                return $this->generateReactHtml($code, $libraryScripts);
            case 'vue':
                return $this->generateVueHtml($code, $libraryScripts);
            case 'html':
                return $code;
            case 'javascript':
                return $this->generateJavaScriptHtml($code, $libraryScripts);
            default:
                throw new \Exception('Unsupported type');
        }
    }

    private function generateReactHtml($code, $libraryScripts)
    {
        return <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    {$libraryScripts}
    <style>
        body { 
            margin: 0; 
            font-family: system-ui, -apple-system, sans-serif;
        }
        #root { min-height: 100vh; }
    </style>
</head>
<body>
    <div id="root"></div>
    <script type="text/babel">
        try {
            {$code}
        } catch (err) {
            document.body.innerHTML = '<div style="color: red; padding: 20px;"><h3>Error:</h3><pre>' + err.message + '</pre></div>';
        }
    </script>
</body>
</html>
HTML;
    }

    private function generateVueHtml($code, $libraryScripts)
    {
        return <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    {$libraryScripts}
    <style>
        body { 
            margin: 0; 
            font-family: system-ui, -apple-system, sans-serif;
        }
    </style>
</head>
<body>
    <div id="app"></div>
    <script>
        try {
            const { createApp } = Vue;
            {$code}
        } catch (err) {
            document.body.innerHTML = '<div style="color: red; padding: 20px;"><h3>Error:</h3><pre>' + err.message + '</pre></div>';
        }
    </script>
</body>
</html>
HTML;
    }

    private function generateJavaScriptHtml($code, $libraryScripts)
    {
        return <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {$libraryScripts}
    <style>
        body { 
            margin: 0; 
            padding: 20px;
            font-family: system-ui, -apple-system, sans-serif;
        }
    </style>
</head>
<body>
    <div id="output"></div>
    <script>
        try {
            {$code}
        } catch (err) {
            document.body.innerHTML = '<div style="color: red;"><h3>Error:</h3><pre>' + err.message + '</pre></div>';
        }
    </script>
</body>
</html>
HTML;
    }
}